name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build lld \
          software-properties-common lsb-release wget
        
    - name: Install LLVM 17
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        
    - name: Run Build Script
      run: |
        export LLVM_BUILD="/usr/lib/llvm-17"
        ./build.sh
        
    - name: Run Unit & Evaluation Tests
      run: |
        ctest --test-dir build
        ./run.sh